name: Kernel Build CI

on:
  push:
    branches:
      - proton
  pull_request:
    branches:
      - proton

jobs:
  build-kernel:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Clone private repo ProtonKernel/ids
        run: |
          git clone https://x-access-token:${{ secrets.IDS_TOKEN }}@github.com/ProtonKernel/ids ../ids

      - name: Build with -tlcRk
        run: |
          export WP="$(realpath $PWD/../)"
          bash build/ckbuild.sh -tlcRk
          echo "ZIP_PATH_K=$ZIP_PATH" >> $GITHUB_ENV
          cp "$ZIP_PATH" ../kernel-build-k.zip

      - name: Upload build with -k
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-k
          path: ../kernel-build-k.zip

      - name: Build with -tlcR
        run: |
          export WP="$(realpath $PWD/../)"
          bash build/ckbuild.sh -tlcR
          echo "ZIP_PATH_NOK=$ZIP_PATH" >> $GITHUB_ENV
          cp "$ZIP_PATH" ../kernel-build-nok.zip

      - name: Upload build sin -k
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-nok
          path: ../kernel-build-nok.zip
